# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."pack1828" = {
    device = "/dev/disk/by-id/scsi-0HC_Volume_102600992";
    fsType = "ext4";
    options = [
      "discard"
      "nofail"
      "defaults"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

