{ pkgs, ... }: {
  nix.extraOptions = ''
    # Generated by https://github.com/DeterminateSystems/nix-installer, version 0.11.0.
    extra-nix-path = nixpkgs=flake:nixpkgs
    experimental-features = nix-command flakes auto-allocate-uids
    build-users-group = nixbld
    bash-prompt-prefix = (nix:$name)\040
  '';

  fonts.fontDir.enable = false; # True will uninstall other fonts, false installs, but doesn't uninstall
  fonts.fonts = [ (pkgs.nerdfonts.override { fonts = [
    "Hack"
    "SourceCodePro"
  ]; }) ];

  programs.zsh.enable = true;

  services.nix-daemon.enable = true;
  system.stateVersion = 4;
  users.users."gene.liverman".home = "/Users/gene.liverman";
  environment = {
    shells = with pkgs; [ bash zsh ];
    loginShell = pkgs.zsh;
    pathsToLink = [
      "/Applications"
      "/share/zsh"
    ];
    systemPackages = with pkgs; [
      coreutils
      #adr-tools
      chart-testing
      colordiff
      dog
      dos2unix
      # dust
      
      subversion
      # git-svn
      
      gotop
      # helm
      hub
      hugo
      
      kopia
      # kubernetes-cli
      kubectx
      mas
      mtr
      nmap
      # node
      openjdk
      rename
      tree
      watch
      wget
      yq
    ];
  };
}

