# rubocop:disable Lint/UnneededDisable, Naming
forge 'http://forge.puppetlabs.com'

# rubocop:disable Metrics/LineLength
# The next line translates to '../../vendor/puppet_modules' aka ~/.dotfiles/vendor/puppet_modules
moduledir "#{File.dirname(File.dirname(File.dirname(__FILE__)))}/vendor/puppet_modules"
# rubocop:enable Metrics/LineLength

mod 'puppetlabs-apt', '4.1.0'
mod 'puppetlabs-stdlib', '4.20.0'
mod 'puppetlabs-vcsrepo', '2.0.0'
mod 'thekevjames-homebrew', '1.7.1'
