# rubocop:disable FileName
forge 'http://forge.puppetlabs.com'

#moduledir '~/.dotfiles/vendor/puppet_modules'
moduledir "#{File.dirname(File.dirname(__FILE__))}/vendor/puppet_modules"

mod 'homebrew',
  :git => 'https://github.com/boxen/puppet-homebrew.git'
mod 'puppetlabs-vcsrepo', '1.5.0'
