{
  imports = [
    ./programs/askpass.nix
    ./programs/audacity.nix
    ./programs/element.nix
    ./programs/firefox.nix
    ./programs/ghostty.nix
    ./programs/gitkraken.nix
    ./programs/handbrake.nix
    ./programs/kopiaui.nix
    ./programs/libreoffice.nix
    ./programs/localsend.nix
    ./programs/logseq.nix
    ./programs/meld.nix
    ./programs/mumble.nix
    ./programs/onepassword.nix
    ./programs/signal.nix
    ./programs/slack.nix
    ./programs/telegram.nix
    ./programs/thunderbird.nix
    ./programs/vivaldi.nix
    ./programs/vscode.nix
    ./programs/zoom.nix
    ./programs/wezterm.nix
    ./services/tailscale.nix
  ];
}
