{
  hostname,
  pkgs,
  username,
  ...
}:
{
  system.primaryUser = username;

  environment = {
    shells = with pkgs; [
      bash
      zsh
    ];
    pathsToLink = [
      "/Applications"
      "/share/zsh"
    ];
    systemPackages = with pkgs; [
      age
      bandwhich
      coreutils
      hugo
      mas
      nmap
      openjdk
      sops
      ssh-to-age
    ];
  };

  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = false; # was true but https://github.com/zhaofengli/nix-homebrew/issues/131
      cleanup = "zap";
      upgrade = true;
    };
    taps = [
      "homebrew-ffmpeg/ffmpeg"
    ];
    brews = [
      # "fastfetch"
      {
        name = "homebrew-ffmpeg/ffmpeg/ffmpeg";
        args = [ "with-srt" ];
      }
      #"firefox-profile-switcher-connector" # having had this on seems to mean I need to toggle browser.profiles.enabled to true in about:config for the new built in profile
      "telnet"
    ];
    casks = [
      "amethyst"
      "angry-ip-scanner"
      "appcleaner"
      "audacity"
      "balenaetcher"
      "bartender"
      #"displaylink"
      "font-hack-nerd-font"
      "font-inconsolata-g-for-powerline"
      "font-source-code-pro-for-powerline"
      "gitkraken"
      "gitkraken-cli"
      "handbrake-app"
      "imageoptim"
      "itermbrowserplugin"
      "iterm2"
      "keepingyouawake"
      #"makemkv" See https://github.com/Homebrew/homebrew-cask/issues/269960
      "meld"
      "mkvtoolnix-app"
      "nextcloud"
      "onlyoffice"
      "raycast"
      "slack"
      "sonos"
      "todoist-app"
      "transmission"
      "zoom"
    ];
    masApps = {
      "BetterSnapTool" = 417375580;
      "Brother iPrint&Scan" = 1193539993;
      "Home Assistant" = 1099568401;
      "LocalSend" = 1661733229;
      "MQTT Explorer" = 1455214828;
    };
  };

  networking.hostName = "${hostname}";

  nix = {
    settings = {
      bash-prompt-prefix = "(nix:$name)\040";
      build-users-group = "nixbld";
      download-buffer-size = 524288000;
      experimental-features = [
        "auto-allocate-uids"
        "flakes"
        "nix-command"
      ];
      extra-substituters = [
        "https://cache.flox.dev"
        "https://cache.numtide.com"
        "https://cache.thalheim.io"
        "https://nix-community.cachix.org"
      ];
      extra-trusted-public-keys = [
        "cache.thalheim.io-1:R7msbosLEZKrxk/lKxf9BTjOOH7Ax3H0Qj0/6wiHOgc="
        "flox-cache-public-1:7F4OyH7ZCnFhcze3fJdfyXYLQw/aV7GEed86nQ7IsOs="
        "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g="
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      ];
      trusted-users = [
        "@admin"
        "${username}"
      ];
    };
    extraOptions = ''
      # Generated by https://github.com/DeterminateSystems/nix-installer, version 0.11.0.
      extra-nix-path = nixpkgs=flake:nixpkgs
      # Uncoment below after validation bug is fixed
      #upgrade-nix-store-path-url = https://install.determinate.systems/nix-upgrade/stable/universal
    '';
  };

  nix-homebrew = {
    trust = {
      taps = [
        "homebrew-ffmpeg/ffmpeg"
      ];
    };
  };

  programs = {
    zsh.enable = true;
  };

  users.users.${username} = {
    home = "/Users/${username}";
    shell = pkgs.zsh;
  };
}
