---
- name: Install packages
  hosts: blue-rock
  vars:
    ansible_python_interpreter: '/usr/local/bin/python3'
  tasks:
    - name: Install packages from Homebrew
      community.general.homebrew:
        state: latest
        name:
          - adr-tools
          # - cdktf
          - chart-testing
          - coreutils
          - dog
          - dust
          - gh
          - gotop
          - helm
          - hub
          - jq
          - k9s
          - kubectl
          - kubectx
          - mas
          - python
          - subversion
          - wget
          - yq

    # - name: Install casks from Homebrew
    #   community.general.homebrew:
    #     state: present
    #     name:
    #       - homebrew/cask/1password
    #       - homebrew/cask/cakebrew
    #       - homebrew/cask/elgato-stream-deck
    #       - homebrew/cask/firefox
    #       - homebrew/cask/google-drive
    #       - homebrew/cask/iterm2
    #       - homebrew/cask/keepingyouawake
    #       - homebrew/cask/logseq
    #       - homebrew/cask/meld
    #       - homebrew/cask/obs
    #       - homebrew/cask/signal
    #       - homebrew/cask/slack
    #       - homebrew/cask/thunderbird
    #       - homebrew/cask/visual-studio-code
    #       - homebrew/cask/whatsapp
    #       - homebrew/cask/zoom
    #       - homebrew/cask-fonts/font-hack-nerd-font
    #       - homebrew/cask-fonts/font-inconsolata-g-for-powerline
    #       - homebrew/cask-fonts/font-source-code-pro-for-powerline
    #       - puppetlabs/puppet/pdk

    # - name: Install apps from App Store
    #   community.general.mas:
    #     state: present
    #     id:
    #       - 1569813296 # 1Password for Safari
    #       - 417375580  # BetterSnapTool
    #       - 1532419400 # MeetingBar for Meet, Zoom & Co
    #       - 1451685025 # WireGuard

    - name: Install packages with pip
      ansible.builtin.pip:
        name:
          - ansible
          - ansible-lint
          # - powerline-status # repalced with airline
          # - psutil

    - name: Download Hack Nerd Font
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip
        dest: "{{ lookup('env', 'HOME') }}/Library/Fonts/"
        remote_src: true

# Vim setup
    - name: Symlink .vimrc
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/repos/dots/link/nix/vimrc"
        dest: "{{ lookup('env', 'HOME') }}/.vimrc"
        state: link
        force: true

    # - name: Symlink .vimrc_os_specific
    #   ansible.builtin.file:
    #     src: "{{ lookup('env', 'HOME') }}/repos/dots/link/mac/vimrc_os_specific"
    #     dest: "{{ lookup('env', 'HOME') }}/.vimrc_os_specific"
    #     state: link
    #     force: true

    - name: Install Vundle
      ansible.builtin.git:
        repo: 'https://github.com/VundleVim/Vundle.vim'
        dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/Vundle.vim"

    - name: Install Vundle Plugins
      shell: "echo -ne '\n' | vim +PluginInstall! +qall"

# ZSH setup
    - name: Clone my oh-my-zsh plugins
      ansible.builtin.git:
        repo: 'https://github.com/genebean/my-oh-zsh-plugins'
        dest: "{{ lookup('env', 'HOME') }}/repos/customized-oh-my-zsh/plugins"

    - name: Clone zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: "{{ lookup('env', 'HOME') }}/repos/customized-oh-my-zsh/plugins/zsh-autosuggestions"

    - name: Clone my oh-my-zsh themes
      ansible.builtin.git:
        repo: 'https://github.com/genebean/my-oh-zsh-themes'
        dest: "{{ lookup('env', 'HOME') }}/repos/customized-oh-my-zsh/themes"

    - name: Symlink .zshrc
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/repos/dots/link/nix/zshrc"
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        state: link
        force: true
