filetype off " required by Vundle. filetype is reenabled after Vundle starts

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required for Vundle to work right
Plugin 'VundleVim/Vundle.vim'

Plugin 'altercation/vim-colors-solarized' " privides solorized color scheme
Plugin 'ekalinin/Dockerfile.vim'          " provides syntax highlighting for Dockerfiles
Plugin 'elzr/vim-json'                    " provides syntax highlighting for JSON files
Plugin 'garbas/vim-snipmate'              " provides code snippets
Plugin 'godlygeek/tabular'                " provides a method for lining things up
Plugin 'honza/vim-snippets'               " provides snippets for use with vim-snipmate
Plugin 'MarcWeber/vim-addon-mw-utils'     " a utility used by vim-snipmate
Plugin 'mrk21/yaml-vim'                   " provides  indentaion and syntax highlighting for yaml
Plugin 'rodjek/vim-puppet'                " provides several niceties for working with Puppet
Plugin 'tomtom/tlib_vim'                  " a utility used by vim-snipmate
Plugin 'vim-ruby/vim-ruby'                " provides syntax hightlighting for ruby files
Plugin 'vim-syntastic/syntastic'          " provides syntax checking

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on    " required for plugins to be able to adjust indent

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
syntax on

set encoding=utf-8
set termencoding=utf-8

set autoindent
set background=dark
set backspace=2
set expandtab
set fillchars+=stl:\ ,stlnc:\
set laststatus=2 " Always display the statusline in all windows
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
set smarttab
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set t_Co=256

let g:solarized_termtrans = 1 " This gets rid of the grey background
colorscheme solarized

" This has to come after colorscheme to not be masked
highlight ColorColumn ctermbg=232
let &colorcolumn=join(range(81,999),",")

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list            = 1
let g:syntastic_check_on_open            = 1
let g:syntastic_check_on_wq              = 0
let g:syntastic_enable_signs             = 1
let g:syntastic_ruby_checkers            = ['rubocop']
let g:syntastic_quiet_messages           = {'level': 'warnings'}
let g:vim_markdown_folding_disabled      = 1

source ~/.vimrc_os_specific
