# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
if [[ `uname` == 'Linux' ]]; then
  ZSH_THEME="af-magic"
else
  ZSH_THEME="beanbag"
  #ZSH_THEME="pygmalion"
  #ZSH_THEME="muse"
fi

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="false"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew bundler gem git git-flow history osx pip python terraform vagrant)

source $ZSH/oh-my-zsh.sh

# User configuration

[ -f ~/.private-env ] && source ~/.private-env || echo '~/.private-env is missing'

# Start GPG agent
export GPG_TTY=$(tty)
gpg-connect-agent /bye
export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh

# export MANPATH="/usr/local/man:$MANPATH"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#alias ll='ls -G -l'
#alias ls='ls -G'
alias sal='ssh-add -L'
alias sz='source ~/.zshrc'
alias ykey='pkill gpg-agent && source ~/.zshrc; ssh-add -L'

export EDITOR='vim'
export POWERLINE_CONFIG_COMMAND='/usr/local/bin/powerline-config'

export PATH=$PATH:~/.nexustools

if [[ `uname` == 'Darwin' ]]; then
  export PATH=$PATH:/usr/local/sbin
  export PATH=$PATH:/Applications/Araxis\ Merge.app/Contents/Utilities
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  export PATH=$PATH:/usr/local/opt/node@6/bin
fi


# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

