{
  imports = [
    ./plasma.nix
    ./programs/askpass.nix
    ./programs/element.nix
    ./programs/firefox.nix
    ./programs/ghostty.nix
    ./programs/kopiaui.nix
    ./programs/libreoffice.nix
    ./programs/localsend.nix
    ./programs/logseq.nix
    ./programs/onepassword.nix
    ./programs/signal.nix
    ./programs/vivaldi.nix
    ./programs/vscode.nix
    ./programs/wezterm.nix
    ./services/tailscale.nix
  ];
}
